### ISSUE TITLE
Port a MacOS build using Mono

### ISSUE THREAD

**Issue by Blakiemon** [DmitriySalnikov/GodotPCKExplorer#1]
I personally have a Mac computer and don't want wait to use my windows Desktop at home every time I feel like doing some RE at school. You can "easily" port to MacOS using https://www.mono-project.com/docs/gui/winforms/porting-winforms-applications/ this.

**Comment by DmitriySalnikov** [comment]
It seemed to me that everything should already work in mono.
Okay, I'll check it out.

**Comment by DmitriySalnikov** [comment]
It looks like mono doesn't have the `GetConsoleWindow` function.
I will try to release an update soon, but first I want to add tests for Linux and macOS, otherwise it may turn out that there are more problems with them.

**Comment by DmitriySalnikov** [comment]
I was completely wrong. On macOS, it is simply impossible to run WinForms anymore because there is no driver for displaying graphics.
I fixed Linux support, which now works just like on Windows.

But on macOS the maximum you can see is:
```
WARNING: The Carbon driver has not been ported to 64bits, and very few parts of Windows.Forms will work properly, or at all
```

Even this simple window cannot be opened on macOS
![image](https://user-images.githubusercontent.com/7782218/185771028-ef865899-0d1f-428e-b7f0-b384b2855714.png)

**Comment by Blakiemon** [comment]
Ah oh well, my appreciation goes out to you for still maintaining this project. I found a way to patch the game I wanted to mod anyway by attaching a script using Godot's --script command line argument.
