### ISSUE TITLE
[question] Recreate the .exe file ? (without .pck but with loose folders)

### ISSUE THREAD

**Issue by Saipan0** [DmitriySalnikov/GodotPCKExplorer#16]
Hi, first of all thank you for your work. Lately I've been encountering games that archive files inside the .exe file (**there are no .pck archives inside the executable but the folders are loose**), can you tell me if there is any way to recreate the exe?

Could this be a new feature to implement?

A thousand thanks.

**Comment by DmitriySalnikov** [comment]
Can you give an example of such a game? I don't quite understand which folders you're talking about.
And by `recreate the .exe` do you mean to pack the game files inside .exe?

**Comment by Saipan0** [comment]
> Can you give an example of such a game? I don't quite understand which folders you're talking about. And by `recreate the .exe` do you mean to pack the game files inside .exe?


I have come across games where there was only the executable and within them, there were two types. The structure of these two types:

1 Exe file - pck file - loose folders (extracted)
2 Exe files - loose folders (extracted)

Now I'll give you the example of this game that I'm trying to translate.

[https://pixeldrain.com/u/qEg5Ludg](File)

I open the exe with your program and extract all the files in a folder and it gave this syntax error, but only for this game, the others work...

![1](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/101728572/e28de70c-f051-4e2d-8ef5-531014359461)

I extract the .exe file and have these folders all loose

![2](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/101728572/a245c801-cdd3-421f-bbd7-2202d3fbeadf)

I modify the files I need and now what can I do to recreate the exe?
If I have to recreate the file this way without having the pck file, how could I do it?

![Screenshot 2024-04-04 002831](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/101728572/95c8315a-de18-46a4-878d-8a9cb5d2f164)

Here is the error, rightly so because there is no pck file. maybe it's a different thing to do

I forgot, with this game sometimes it didn't give me the syntax error when extracting. so I don't know what it could be..

**Comment by DmitriySalnikov** [comment]
<details>

What's wrong with Godot? Why is it writing files multiple times? After all, if they have the same name, then only one of the files will be used... I made this renaming system because I met a duplicate file in `Window Kill`, but I didn't think there could be so many of them -_-
```
[04/04/2024 01:50:16]   [Progress] Open PCK: Duplicate file found. It will be renamed 'res://dialogic/timelines/timeline-1710956045.json' -> 'res://dialogic/timelines/timeline-1710956045.duplicate_1.json'
[04/04/2024 01:50:16]   [Progress] Open PCK: Duplicate file found. It will be renamed 'res://dialogic/timelines/timeline-1710955955.json' -> 'res://dialogic/timelines/timeline-1710955955.duplicate_1.json'
[04/04/2024 01:50:16]   [Progress] Open PCK: Duplicate file found. It will be renamed 'res://dialogic/timelines/timeline-1710955686.json' -> 'res://dialogic/timelines/timeline-1710955686.duplicate_1.json'
[04/04/2024 01:50:16]   [Progress] Open PCK: Duplicate file found. It will be renamed 'res://dialogic/timelines/timeline-1710955639.json' -> 'res://dialogic/timelines/timeline-1710955639.duplicate_1.json'
[04/04/2024 01:50:16]   [Progress] Open PCK: Duplicate file found. It will be renamed 'res://dialogic/timelines/timeline-1710955632.json' -> 'res://dialogic/timelines/timeline-1710955632.duplicate_1.json'
```

</details>

---

> ![1](https://private-user-images.githubusercontent.com/101728572/319378320-e28de70c-f051-4e2d-8ef5-531014359461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODQ3NDAsIm5iZiI6MTcxMjE4NDQ0MCwicGF0aCI6Ii8xMDE3Mjg1NzIvMzE5Mzc4MzIwLWUyOGRlNzBjLWYwNTEtNGUyZC04ZWY1LTUzMTAxNDM1OTQ2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QyMjQ3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODg4NDRhOWZmYmVjMDlkMGNkM2QwYTUyNTI3NjNiZmQ2N2VmY2VkNTdhMDIzNzdjMzk1ODA0MTg3ZThjNjcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.msavFb_aA5qit6a3RbFwjpRaLp-BUXBcvtoUxDTUtOI)

Here in the screenshot you can see that the developer somehow managed to put files with the path `user://` into the PCK.

![image](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/2933210f-25b6-47cb-a2ad-c51bdfbaab0d)

It's not that much of a problem to manually specify absolutely any path to the resource, but how can this be done from the editor during export!?

---

> ![Screenshot 2024-04-04 002831](https://private-user-images.githubusercontent.com/101728572/319381363-95c8315a-de18-46a4-878d-8a9cb5d2f164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxODQ3NDAsIm5iZiI6MTcxMjE4NDQ0MCwicGF0aCI6Ii8xMDE3Mjg1NzIvMzE5MzgxMzYzLTk1YzgzMTVhLWRlMTgtNDZhNC04NzhkLThhOWNiNWQyZjE2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QyMjQ3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDYwYjc1NDM5ZDQyZDhkNmNlNjMwYTg3MWIxY2EyY2QzYWNlZWY3ZWU5NjcwMDMxNzgyMjE4OTNlYjY3Yjc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WapEdOxvusz244XXxgjOTSt2Q4Rz2d9lUfAAxbh-eUE)
>
>Here is the error, rightly so because there is no pck file. maybe it's a different thing to do

PCK is inside the EXE, that is, embedded.

You just need to remove the PCK from the original EXE.
![image](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/227ba966-69ae-4c1b-8fb6-96b02833b2bf)

And don't forget to specify the correct version of the PCK before packing:
![image](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/d4b29c20-b0f5-4f5b-adc5-ee349695a8b7)

I managed to successfully change the main scene:
![image](https://github.com/DmitriySalnikov/GodotPCKExplorer/assets/7782218/c9e695a8-1440-42a9-9890-4016e131918a)
(but as I understand it, for some reason it is impossible to change the file size in bytes)
I was also able to launch and play without any problems.

---

I found a couple of problems with `user://` and packing, but in this situation they should not prevent the content from changing.
I'll also consider adding an option to quickly replace PCKs when packing.

**Comment by Saipan0** [comment]
[Dmitriy](https://github.com/DmitriySalnikov) It works perfectly. A thousand thanks
I thought there was no .pck file here, but it was embedded. 
It didn't give me any user:// errors when packing.
Thanks so much again, very kind. 
I sent you an email with a particular question.
