### ISSUE TITLE
[Bug]: Encryption key is required, but PCKBruteformer shows no encryption

### ISSUE THREAD

**Issue by fatecyx** [DmitriySalnikov/GodotPCKExplorer#20]
### Commit or version

a36d309 

### On which operating systems the error occurs

Windows

### Issue description

When I attempt to "extract all," it prompts me for an encryption key. However, PCKBruteforcer indicates that the file is not encrypted. This discrepancy is confusing. I have attached the file for your reference.

https://drive.google.com/file/d/1VzilYM4a4LfHKDUNoUL63_-1CWDjToyE/view?usp=drive_link

Thank you for your assistance!

### Steps to reproduce

N/A

**Comment by DmitriySalnikov** [comment]
> When I attempt to "extract all," it prompts me for an encryption key.

For me, this happens at the end of the process, which means that only a few files are encrypted and were packed at the very end.
For some reason, I forgot during development that Godot has filters and not all files can really be encrypted in it 😅
![image](https://github.com/user-attachments/assets/201328bb-e1e0-424f-89bc-e915a99a0fc0)

And the funny thing is that the game developer most likely wanted to encrypt the entire game, but did it only for the icon :)
![image](https://github.com/user-attachments/assets/d0bea068-ee0a-42b2-bd40-bbcaee8c40a1)


> However, PCKBruteforcer indicates that the file is not encrypted.

This is expected, because I take into account all files when choosing the one suitable for brute force, and not just those that are encrypted.

https://github.com/DmitriySalnikov/GodotPCKExplorer/blob/a36d30958b832e30a5e013d655a285fff765d09f/Bruteforcer/PCKBruteforcer/Bruteforcer.cs#L173-L174

I will fix both Bruteforcer and most likely PCK Explorer, I will make it check immediately when extracting/opening for the presence of separate encrypted files.
