### ISSUE TITLE
[Bug]: Opening .exe immediately closes itself

### ISSUE THREAD

**Issue by OrtonLongGaming2** [DmitriySalnikov/GodotPCKExplorer#22]
### Commit or version

1.5.0

### On which operating systems the error occurs

Windows

### Issue description

Double clicking .exe, asks permission to run or whatever, hit yes, I see something flash in the toolbar and then it immediately closes.

### Steps to reproduce

Opening .exe - wind x64 and wind x86 native versions 1.5.0

**Comment by DmitriySalnikov** [comment]
Can you provide Logs? Logs are stored at the path: `%APPDATA%\GodotPCKExplorer`

**Comment by DmitriySalnikov** [comment]
Do you still have a problem?

**Comment by st-arti-17** [comment]
I do, there you go
[log_c.txt](https://github.com/user-attachments/files/17777421/log_c.txt)

**Comment by DmitriySalnikov** [comment]
> I do, there you go
> [log_c.txt](https://github.com/user-attachments/files/17777421/log_c.txt)

Thanks, but these are logs from `.Console.exe`, which is designed to work with the console. At startup, a new console window opens and closes immediately. To work with this version, you need to manually open the console window and run the program from it.

For example: press Win + X to open the system menu - select Windows PowerShell or Console - and in this console window enter the full path to `.Console.exe` (you can just drag the program to the console).

To work with the graphical interface, you need to run `.UI.exe`.

> ### Steps to reproduce
> Opening .exe - wind x64 and wind x86 **native** versions 1.5.0

Oh, the first time I read this message, I didn't pay enough attention to this line. Native versions, as mentioned in the name, work only in the console.

I could make a native version with a UI for Windows, but it doesn't make sense, since then the program will take up more than 162MB.
